DROP DATABASE IF EXISTS GuessTheNumberDBTest;
CREATE DATABASE GuessTheNumberDBTest;
USE GuessTheNumberDBTest;

CREATE TABLE Game (
	GameId INT PRIMARY KEY AUTO_INCREMENT,
	Answer VARCHAR(4) NOT NULL,
	GameInProgress BOOLEAN NOT NULL
);

CREATE TABLE Guess (
	guessId INT PRIMARY KEY AUTO_INCREMENT,
	`Time` DATETIME NOT NULL,
	Answer VARCHAR(4) NOT NULL,
	Result VARCHAR(8) NOT NULL,
	GameId INT NOT NULL,
	CONSTRAINT fk_Guess_Game FOREIGN KEY (GameId)
		REFERENCES Game(GameId)
);